### ISSUE TITLE
Using json-errors for flycheck

### ISSUE THREAD

**Issue by user471** [emacs-pe/purescript-mode#1]
Are there any plans to use ```--json-errors``` flag from purescript 0.8?
For example, right now psc checker cannot separate warnings and errors.

**Comment by bsermons** [comment]
I started working on flycheck json support here: https://github.com/bsermons/flycheck-purescript

It's a separate project for now since I am using the purescript mode included in spacemacs which uses a different purescript-mode.

**Comment by user471** [comment]
What is the current state of the project?

**Comment by bsermons** [comment]
Just created it yesterday so hasn't been tested much.  Was working for the
single file I was using to test though for showing errors.

**Comment by marsam** [comment]
I totally missed the v0.8 release, I'll work on this this weekend, also I think I can split flycheck-purescript to be independent of the purescript-mode

**Comment by marsam** [comment]
Hi, I've updated flycheck-purescript to use --json-errors and now is independent from the purescript-mode, please give it a try.

**Comment by user471** [comment]
@marsam Thanks. What is the reason to use ` "--output" temporary-directory`? I think It should be customization.
Also, filter for types of warnings would be nice, something like
```(setq flycheck-purescript-ignore-warnings '("MissingTypeDeclaration"))```

**Comment by marsam** [comment]
> What is the reason to use "--output" temporary-directory? I think It should be customization.

There is no special reason behind it, I'll make it customizable

> Also, filter for types of warnings would be nice, something like `(setq flycheck-purescript-ignore-warnings '("MissingTypeDeclaration"))`

Nice idea :+1:, I'll add it later

**Comment by marsam** [comment]
I've added this features and move it flycheck-purescript to is own repository https://github.com/emacs-pe/flycheck-purescript, please give it a try

**Comment by user471** [comment]
Thanks. Everything works fine.

**Comment by user471** [comment]
Turns out ```temporary-directory``` is bad idea.  PureScript uses output directory as cache for incremental compilation, but Flycheck can create new directory instead of using old one. So in this case psc need to recompile whole project and dependencies. So I think default output should be output directory in project root.

**Comment by marsam** [comment]
For large projects certainly can be slow, but I prefer the default to use
`temporary-directory`, instead of silently overwriting the “output” directory.

btw, I’ve updated the package to allow the compilation directory to be relative
to the project root.
