### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by epost** [emacs-pe/purescript-mode#2]
Would be cool to have a few lines of elisp and/or shell cmds or something to get going.

**Comment by marsam** [comment]
Hi, thanks for trying this mode, I'll add documentation this weekend, in the meantime, you can use:

```elisp
(add-to-list 'load-path "/path/to/purescript-mode/")
(require 'purescript-mode)
(require 'psci)                         ; warn: melpa has a different psci package
(require 'flycheck-purescript)
(with-eval-after-load 'flycheck (flycheck-purescript-setup))
```

for indentation, you can use the available ones for haskell mode, e.g. [hyai](https://github.com/iquiw/hyai):

```elisp
(add-hook 'purescript-mode-hook #'hyai-mode)
```

**Comment by epost** [comment]
Thanks!

**Comment by marsam** [comment]
I've added the installation steps https://github.com/emacs-pe/purescript-mode#installation
please tell me if works for you

**Comment by epost** [comment]
Yeah, I got it running, thanks a lot! :)
